name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Change to your default branch
  workflow_dispatch:   # Allows manual trigger from GitHub UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      page_url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      
      # Build your site here if needed. For example, with React + Vite:
      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build   # Change to your build output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ needs.build.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v1
